### ISSUE TITLE
bug: Cannot invoke "net.minecraft.class_1132.method_3818()" because the return value of "net.minecraft.class_310.method_1576()" is null

### ISSUE THREAD

**Issue by ChrqnosMC** [42atomys/fabric-advancementinfo-reloaded#26]
### Describe the Bug

A value is not received or is received as null, so the advancements page doesn't load/generate correctly ? I imagine, and causes my game to crash every time I want to access the main menu while connected to a single-player or server world.

### Steps to Reproduce

I just pressed Esc to return to the menu and my game stopped.

### Expected Behavior

Accessing the advancements menu

### Modloader Type

Fabric

### Modloader Version

0.16.7

### Mod Version

0.5.0+fabric-mc1.21.1

### Log Output

```shell
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2024-10-14 04:14:18
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1132.method_3818()" because the return value of "net.minecraft.class_310.method_1576()" is null
	at knot//net.minecraft.class_5522.method_31350(class_5522.java:274)
	at knot//net.minecraft.class_5522.<init>(class_5522.java:82)
	at knot//net.minecraft.class_433.method_57733(class_433.java:104)
	at knot//net.minecraft.class_433.modify$zzb000$advancements_reloaded$modifyAdvancementsButton(class_433.java:3040)
	at knot//net.minecraft.class_433.method_20543(class_433.java:104)
	at knot//net.minecraft.class_433.method_25426(class_433.java:68)
	at knot//net.minecraft.class_437.method_25423(class_437.java:309)
	at knot//net.minecraft.class_310.method_1507(class_310.java:1143)
	at knot//net.minecraft.class_310.method_20539(class_310.java:1721)
	at knot//net.minecraft.class_309.method_1466(class_309.java:451)
	at knot//net.minecraft.class_309.method_22678(class_309.java:499)
	at knot//net.minecraft.class_1255.execute(class_1255.java:108)
	at knot//net.minecraft.class_309.method_22676(class_309.java:499)
	at knot//org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:303)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1307)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at knot//net.minecraft.class_310.modify$eon000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:26755)
	at knot//net.minecraft.class_310.method_1514(class_310.java:905)
	at knot//fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at knot//net.minecraft.class_310.modify$eon000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:26755)
	at knot//net.minecraft.class_310.method_1514(class_310.java:905)
	at knot//fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at knot//net.minecraft.class_310.modify$eon000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:26744)
	at knot//net.minecraft.class_310.method_1514(class_310.java:902)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.4, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1339822456 bytes (1277 MiB) / 2659188736 bytes (2536 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 27.20.100.8729
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 4096.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 38753.18
	Virtual memory used (MiB): 25967.00
	Swap memory total (MiB): 22528.00
	Swap memory used (MiB): 883.66
	Space in storage for jna.tmpdir (MiB): available: 153540.47, total: 487548.31
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 153540.47, total: 487548.31
	Space in storage for io.netty.native.workdir (MiB): available: 153540.47, total: 487548.31
	Space in storage for java.io.tmpdir (MiB): available: 153540.47, total: 487548.31
	Space in storage for workdir (MiB): available: 153540.47, total: 487548.31
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192M
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.6.6
		advancements_reloaded: Advancements Reloaded 0.5.0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.8
		authme: Auth Me 8.0.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
		badoptimizations: BadOptimizations 2.1.4
		betterf3: BetterF3 11.0.1
		bettermounthud: Better Mount HUD 1.2.4
		betterstats: Better Statistics Screen 3.13.2+fabric-1.21
		block-entity-extended-rendering: Block Entity Extended Rendering 4.0.0
			obsidianui: ObsidianUI 0.2.7+mc1.21
		bobby: Bobby 5.2.4+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		brb: Better Recipe Book 1.10.0-rc5+1.21
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.109+1.21
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.109+1.21
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.109+1.21
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.109+1.21
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.109+1.21
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.109+1.21
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.109+1.21
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.109+1.21
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.109+1.21
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.109+1.21
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.109+1.21
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.109+1.21
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.109+1.21
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.109+1.21
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.109+1.21
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		carpet: Carpet Mod 1.4.147+v240613
		cherishedworlds: Cherished Worlds 10.0.2+1.21.1
		chunky: Chunky 1.4.16
		citresewn: CIT Resewn 1.2.1+1.21
			citresewn-defaults: CIT Resewn: Defaults 1.2.1+1.21
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.84
		cubes-without-borders: Cubes Without Borders 2.1.1+1.21
		datapackinstaller: Datapack Installer 2.0.0
		dynamic_fps: Dynamic FPS 3.7.3
			net_lostluma_battery: battery 1.1.0
		eclipsestweakeroo: Eclipse's Tweakeroo Additions 0.5.2-1.21.1
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		entity_model_features: Entity Model Features 2.2.6
		entity_sound_features: Entity Sound Features 0.4
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		evilcreativefly: Creative Fly 1.4.3-1.21-fabric
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fallingleaves: Falling Leaves 1.16.2
		fastipping: Fast IP Ping 1.0.5
		fastquit: FastQuit 3.0.0+1.20.6
		ferritecore: FerriteCore 7.0.0
		forgeconfigapiport: Forge Config API Port 21.0.8
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		highlight: Highlight 3.0.0
			resourcefullib: Resourceful Lib 3.0.1
				com_teamresourceful_bytecodecs: bytecodecs 1.1.0
				com_teamresourceful_yabn: yabn 1.0.3
		iceberg: Iceberg 1.2.7
		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.35+mc1.21
		ingamestats: InGameStats 1.1.1+mc1.21.1
		inventory_control_tweaks: Inventory Control Tweaks 1.4.1
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		isometric-renders: Isometric Renders 0.4.7+1.21
			worldmesher: Worldmesher 0.4.6+1.21
		itemscroller: Item Scroller 0.24.50
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		ktnilcks: ItemLocks 1.21-1.3.9
		lightoverlay: Light Overlay 12.0.0
		litematica: Litematica 0.19.50
		lithium: Lithium 0.13.1
		malilib: MaLiLib 0.21.0
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.32.50
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.19.1+mc1.21
		modmenu: Mod Menu 11.0.2
		more_vault: More Vault 1.0-1.21
		moreculling: More Culling 0.26.0
			com_github_fallen-breath_conditional-mixin: conditional-mixin v0.6.2
			mixinsquared: MixinSquared 0.1.1
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		notenoughcrashes: Not Enough Crashes 4.4.8+1.21
		nvidium: Nvidium 0.3.1
		owo: oωo 0.12.15+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		packrule-menus: Pack/Rule Menus 2.0.1+1.21
		placeholder-api: Placeholder API 2.4.1+1.21
		preventer: Preventer 1.2.0
		raised: Raised 4.0.0
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		screenshot_organisation: Screenshot Organisation 1.8
			shared-resources-api: Shared Resources API 1.8.0
		screenshotclipboard: Screenshot to Clipboard 1.0.10
		scribble: Scribble 1.3.1
		servercore: ServerCore 1.5.4+1.21
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			org_yaml_snakeyaml: snakeyaml 2.2
			space_arim_dazzleconf_dazzleconf-core: dazzleconf-core 1.3.0-M2
			space_arim_dazzleconf_dazzleconf-ext-snakeyaml: dazzleconf-ext-snakeyaml 1.3.0-M2
		shulkerboxtooltip: Shulker Box Tooltip 5.1.1+1.21
		skinlayers3d: 3d-Skin-Layers 1.6.7
		skinshuffle: SkinShuffle 2.2.2+1.21
			com_konghq_unirest-java_standalone: unirest-java 3.11.9
			commons-validator_commons-validator: commons-validator 1.7
			org_jsoup_jsoup: jsoup 1.16.1
			org_mineskin_java-client: java-client 1.2.4-SNAPSHOT
			spruceui: SpruceUI 5.1.0+1.21
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		soundcontroller: Sound Controller 1.1.3
		spark: spark 1.10.109
		sspb: Sodium Shadowy Path Blocks 3.4.0
		superflatworldnoslimes: Superflat World No Slimes 3.4
		tcdcommons: TCD Commons API 3.12.3+fabric-1.21
		text-formatting-everywhere: Text Formatting Everywhere 1.0.1
		tweakermore: TweakerMore 3.21.0
			conditional-mixin: conditional mixin 0.6.3
		tweakeroo: Tweakeroo 0.21.50
		vcinteraction: Voice Chat Interaction 1.21.1-1.0.8
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.9+1.21
		villagerconfig: VillagerConfig 4.3.0+1.21.1
			config2brigadier: Config to Brigadier 1.2.5
			fiber: fiber 0.23.0-2
		voicechat: Simple Voice Chat 1.21.1-2.5.24
		wi_zoom: WI Zoom 1.5-MC1.21
		worldedit: WorldEdit 7.3.7+6929-c6af3a3
		xaerobetterpvp: Better PVP 24.5.0
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	Client Crashes Since Restart: 4
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Not Enough Crashes (notenoughcrashes), Advancements Reloaded (advancements_reloaded)
```

### Additional Context

I tried it on an earlier version and it seems to be a bug only on this version 0.5.0+fabric-mc1.21.1.

**Comment by 42atomys** [comment]
Hi thanks for your report I will check that

**Comment by 42atomys** [comment]
Hi again @ChrqnosMC, I try to install all mods of your log file and I don't have the issue. Can you attach a zip file with your mod folders please ?  With the mods folder I will can maybe reproduce your error !

**Comment by Hlebuw3k** [comment]
https://mclo.gs/F22zp8b
Possibly related to https://github.com/astei/krypton/issues/152 as cannot reproduce this issue after disabling Advancements Reloaded, OR e4mc, OR Krypton, OR without joining a singleplayer world first.
1. Join singleplayer world, get disconnected due to above issue.
2. Join multiplayer server.
3. Press ESC to crash.
