### ISSUE TITLE
chore: add support for 1.21.2 / 1.21.3

### ISSUE THREAD

**Issue by yungieamongie** [42atomys/fabric-advancementinfo-reloaded#34]
### Describe the Bug

can't open the advancement menu :sob:

### Steps to Reproduce

1. Download the 0.6.1 version for fabric
2. Launch the game on 1.21.2 fabric
3. Try to open the advancement menu

### Expected Behavior

1. Observe whether you should be able to view the advancement menu or not

### Modloader Type

Fabric

### Modloader Version

fabric-loader-0.16.7-1.21.2

### Mod Version

advancementinfo-reloaded-0.6.1-fabric-1.21.1 (although it says 1.21.x when downloading it)

### Log Output

```shell
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2024-10-24 00:23:31
Description: Rendering screen

java.lang.NoSuchMethodError: 'void net.minecraft.class_332.method_52706(net.minecraft.class_2960, int, int, int, int)'
	at knot//codes.atomys.advr.screens.AdvancementReloadedWidget.renderWidgets(AdvancementReloadedWidget.java:303)
	at knot//codes.atomys.advr.screens.AdvancementReloadedTab.render(AdvancementReloadedTab.java:313)
	at knot//codes.atomys.advr.screens.AdvancementReloadedScreen.drawAdvancementTree(AdvancementReloadedScreen.java:522)
	at knot//codes.atomys.advr.screens.AdvancementReloadedScreen.method_25394(AdvancementReloadedScreen.java:460)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$57(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$zpa000$fabric-screen-api-v1$onRenderScreen(class_757.java:912)
	at knot//net.minecraft.class_757.method_3192(class_757.java:549)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//codes.atomys.advr.screens.AdvancementReloadedWidget.renderWidgets(AdvancementReloadedWidget.java:303)
	at knot//codes.atomys.advr.screens.AdvancementReloadedTab.render(AdvancementReloadedTab.java:313)
	at knot//codes.atomys.advr.screens.AdvancementReloadedScreen.drawAdvancementTree(AdvancementReloadedScreen.java:522)
	at knot//codes.atomys.advr.screens.AdvancementReloadedScreen.method_25394(AdvancementReloadedScreen.java:460)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$57(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$zpa000$fabric-screen-api-v1$onRenderScreen(class_757.java:912)

-- Screen render details --
Details:
	Screen name: codes.atomys.advr.screens.AdvancementReloadedScreen
	Mouse location: Scaled: (213, 120). Absolute: (427.000000, 240.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at knot//net.minecraft.class_757.method_3192(class_757.java:549)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 45.382s
	Wall uptime: 33.867s
	High-res time: 31.290s
	Client ticks: 459 ticks / 22.950s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:954)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['yungie'/2, l='ClientLevel', x=384.46, y=146.89, z=312.77]]
	Chunk stats: 1521, 1021
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,167,0), Section: (at 0,7,0 in 0,10,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1199492 game time, 1243 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 45

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Blue Ancient Debris 1.20.zip, fabric, advancements_reloaded, cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, sodium, yet_another_config_lib_v3, zoomify

-- System Details --
Details:
	Minecraft Version: 1.21.2
	Minecraft Version ID: 1.21.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 613772024 bytes (585 MiB) / 1409286144 bytes (1344 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5500U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 30.0.14064.6002
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 23370.43
	Virtual memory used (MiB): 15167.67
	Swap memory total (MiB): 8192.00
	Swap memory used (MiB): 374.05
	Space in storage for jna.tmpdir (MiB): available: 7622.80, total: 101873.31
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 7622.80, total: 101873.31
	Space in storage for io.netty.native.workdir (MiB): available: 7622.80, total: 101873.31
	Space in storage for java.io.tmpdir (MiB): available: 7622.80, total: 101873.31
	Space in storage for workdir (MiB): available: 7622.80, total: 101873.31
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancements_reloaded: Advancements Reloaded 0.6.0
		cloth-config: Cloth Config v16 16.0.141
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.86
		fabric-api: Fabric API 0.106.1+1.21.2
			fabric-api-base: Fabric API Base 0.4.48+c47b9d4373
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.78+c47b9d4373
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.5+c47b9d4373
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+c47b9d4373
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+c47b9d4373
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.2+c47b9d4373
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.22+c47b9d4373
			fabric-command-api-v1: Fabric Command API (v1) 1.2.56+f71b366f73
			fabric-command-api-v2: Fabric Command API (v2) 2.2.35+c47b9d4373
			fabric-commands-v0: Fabric Commands (v0) 0.2.73+df3654b373
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.5+c47b9d4373
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.0+7f945d5b73
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.0+c47b9d4373
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+c47b9d4373
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.38+c47b9d4373
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.14+c47b9d4373
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+c47b9d4373
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.5+c47b9d4373
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.9+c47b9d4373
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4373
			fabric-item-api-v1: Fabric Item API (v1) 11.1.5+c47b9d4373
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.15+e7c9ab6673
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+c47b9d4373
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b373
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.22+c47b9d4373
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.24+3f89f5a573
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.12+c47b9d4373
			fabric-message-api-v1: Fabric Message API (v1) 6.0.19+c47b9d4373
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.7+c47b9d4373
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.3+56ec7ac673
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.7+c47b9d4373
			fabric-particles-v1: Fabric Particles (v1) 4.0.8+c47b9d4373
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.2+c47b9d4373
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+56ec7ac673
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.3+c47b9d4373
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.3+c47b9d4373
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e73
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.13+c47b9d4373
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.81+df3654b373
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.5+c47b9d4373
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+c47b9d4373
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.5+c47b9d4373
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.32+c47b9d4373
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.98+c47b9d4373
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+c47b9d4373
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.0+c47b9d4373
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+c47b9d4373
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		gammautils: Gamma Utils 2.2.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.2
		sodium: Sodium 0.6.0-beta.3+mc1.21.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21.2-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.2+1.21.3
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.2
	Launched Version: fabric-loader-0.16.7-1.21.2
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.14802 Core Profile Forward-Compatible No Error Context 21.40.64.06 30.0.14064.6002, ATI Technologies Inc.
	Window size: 854x480
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 16/16 chunks
	Resource Packs: vanilla, file/Blue Ancient Debris 1.20.zip (incompatible), fabric, advancements_reloaded, cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, sodium, yet_another_config_lib_v3 (incompatible), zoomify
	Current Language: en_gb
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 5500U with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['yungie'/2, l='ServerLevel[IanXO4 Ghast Farm - 30 portals]', x=384.46, y=146.89, z=312.77]]
	Active Data Packs: vanilla, fabric, collective, fabric-convention-tags-v2
	Available Data Packs: collective, fabric, fabric-convention-tags-v2, minecart_improvements, redstone_experiments, trade_rebalance, vanilla, winter_drop
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -7002193343634540818
	Suppressed Exceptions: ~~NONE~~
```

### Additional Context

even if this an obvious glitch because "the version is outdated" this is a reminder idk, feel free to close if you think its useless spam

**Comment by 42atomys** [comment]
Hi, I think this is because the mod aren't updated yet to 1.21.2 and 1.21.3 :) 

Dont worry the support will be available in few days

**Comment by 42atomys** [comment]
The support are scheduled for next week, thanks for your patience
